### ISSUE TITLE
Delete item throws an Exception

### ISSUE THREAD

**Issue by debbabi** [cristal-ise/jooqdb#11] opened 2017-06-06 13:33 UTC
````
ERROR  : ClusterStorageManager.delete() - writer JOOQ:POSTGRES ClusterStorage could not delete /entity/dace544c-5481-45f3-be27-f1538618e023/Property/Type/Type: IDL:org.cristalise.kernel/common/PersistencyException:1.0  Invalid number of primary keys:[Type, Type]
JooqClusterStorage.abort(DISABLED) - autoCommit:true
ERROR  : TransactionManager.commit() - Problems during transaction commit of locker org.cristalise.kernel.lifecycle.instance.Workflow@9fccfa1. Database may be in an inconsistent state.
Delete at AuditTrail/1/1 in /entity/dace544c-5481-45f3-be27-f1538618e023
EXCEPTION:org.cristalise.kernel.common.PersistencyException: IDL:org.cristalise.kernel/common/PersistencyException:1.0  Invalid number of primary keys (max 1):[1, 1]
	at org.cristalise.storage.jooqdb.clusterStore.JooqHistoryHandler.getPKConditions(JooqHistoryHandler.java:96)
	at org.cristalise.storage.jooqdb.JooqHandler.delete(JooqHandler.java:120)
	at org.cristalise.storage.jooqdb.JooqClusterStorage.delete(JooqClusterStorage.java:266)
	at org.cristalise.kernel.persistency.ClusterStorageManager.remove(ClusterStorageManager.java:385)
	at org.cristalise.kernel.persistency.TransactionManager.commit(TransactionManager.java:228)
	at org.cristalise.kernel.lifecycle.instance.Activity.request(Activity.java:218)
	at org.cristalise.kernel.lifecycle.instance.Workflow.requestAction(Workflow.java:136)
	at org.cristalise.kernel.entity.ItemImplementation.delegatedAction(ItemImplementation.java:199)
	at org.cristalise.kernel.entity.ItemImplementation.requestAction(ItemImplementation.java:182)
	at org.cristalise.kernel.entity.TraceableEntity.requestAction(TraceableEntity.java:126)
	at org.cristalise.kernel.entity.ItemPOA._invoke(ItemPOA.java:177)
	at com.sun.corba.se.impl.protocol.CorbaServerRequestDispatcherImpl.dispatchToServant(CorbaServerRequestDispatcherImpl.java:654)
	at com.sun.corba.se.impl.protocol.CorbaServerRequestDispatcherImpl.dispatch(CorbaServerRequestDispatcherImpl.java:205)
	at com.sun.corba.se.impl.protocol.CorbaMessageMediatorImpl.handleRequestRequest(CorbaMessageMediatorImpl.java:1700)
	at com.sun.corba.se.impl.protocol.CorbaMessageMediatorImpl.handleRequest(CorbaMessageMediatorImpl.java:1558)
	at com.sun.corba.se.impl.protocol.CorbaMessageMediatorImpl.handleInput(CorbaMessageMediatorImpl.java:940)
	at com.sun.corba.se.impl.protocol.giopmsgheaders.RequestMessage_1_2.callback(RequestMessage_1_2.java:198)
	at com.sun.corba.se.impl.protocol.CorbaMessageMediatorImpl.handleRequest(CorbaMessageMediatorImpl.java:712)
	at com.sun.corba.se.impl.transport.SocketOrChannelConnectionImpl.dispatch(SocketOrChannelConnectionImpl.java:471)
	at com.sun.corba.se.impl.transport.SocketOrChannelConnectionImpl.doWork(SocketOrChannelConnectionImpl.java:1230)
	at com.sun.corba.se.impl.orbutil.threadpool.ThreadPoolImpl$WorkerThread.performWork(ThreadPoolImpl.java:490)
	at com.sun.corba.se.impl.orbutil.threadpool.ThreadPoolImpl$WorkerThread.run(ThreadPoolImpl.java:519)
````

**Comment by kovax** [comment] 2017-08-29 18:58
Duplicate of #16

**Closed by kovax** 2017-08-29 18:58 UTC
Labels: duplicate
